'use client';
import { FormEvent, useEffect, useState } from 'react';

type Resume = { id: string; title: string; versions: Array<{ id: string; originalName: string; status: string; createdAt: string }> };
const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:4000/v1';
export function ResumeWorkspace() {
  const [resumes, setResumes] = useState<Resume[]>([]); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const load = () => fetch(`${apiUrl}/resumes`, { credentials: 'include' }).then((r) => r.ok ? r.json() : Promise.reject()).then(setResumes).catch(() => setMessage('Please sign in to manage resumes.'));
  useEffect(() => { load(); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const title = String(form.get('title') ?? '').trim(); const file = form.get('file'); if (!(file instanceof File) || !file.size) return setMessage('Choose a PDF file first.'); setBusy(true); setMessage(''); try { const created = await fetch(`${apiUrl}/resumes`, { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title }) }); if (!created.ok) throw new Error('Could not create resume.'); const resume = await created.json() as Resume; const upload = new FormData(); upload.append('file', file); const saved = await fetch(`${apiUrl}/resumes/${resume.id}/versions`, { method: 'POST', credentials: 'include', body: upload }); if (!saved.ok) throw new Error('Upload failed. Use a PDF smaller than 5 MB.'); event.currentTarget.reset(); setMessage('Resume uploaded securely.'); load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Upload failed.'); } finally { setBusy(false); } }
  return <main className="resume-page"><p className="eyebrow">RESUME WORKSPACE</p><h1>Upload a resume</h1><p className="muted">PDF files only, up to 5 MB. Your files are private to your account.</p><form className="upload-form" onSubmit={submit}><label>Resume title<input name="title" required maxLength={120} placeholder="Software engineer resume" /></label><label>PDF file<input name="file" type="file" accept="application/pdf" required /></label><button disabled={busy}>{busy ? 'Uploading…' : 'Upload resume'}</button></form>{message && <p className="form-message">{message}</p>}<section><h2>Your resumes</h2>{resumes.length === 0 ? <p className="empty">No resumes uploaded yet.</p> : <ul className="resume-list">{resumes.map((resume) => <li key={resume.id}><strong>{resume.title}</strong><span>{resume.versions[0] ? `${resume.versions[0].originalName} · ${resume.versions[0].status}` : 'No file uploaded'}</span></li>)}</ul>}</section></main>;
}
