'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { FormEvent, useState } from 'react';

const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:4000/v1';
type Mode = 'login' | 'register' | 'forgot-password' | 'reset-password' | 'verify-email';
export function AuthCard({ mode }: { mode: Mode }) {
  const router = useRouter(); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const title = { login: 'Welcome back', register: 'Create your account', 'forgot-password': 'Reset your password', 'reset-password': 'Choose a new password', 'verify-email': 'Verify your email' }[mode];
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(''); const values = Object.fromEntries(new FormData(event.currentTarget)); const endpoint = mode === 'login' ? 'login' : mode === 'register' ? 'register' : mode; try { const response = await fetch(`${apiUrl}/auth/${endpoint}`, { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(values) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message ?? 'Something went wrong.'); if (mode === 'login') router.push('/dashboard'); else if (mode === 'register') setMessage(data.verificationToken ? `Development verification token: ${data.verificationToken}` : 'Account created. Check your email to verify it.'); else setMessage('Request completed.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Something went wrong.'); } finally { setBusy(false); } }
  return <main className="auth-page"><section className="auth-card"><Link className="brand" href="/">placement<span>mentor</span></Link><p className="eyebrow">CAREER PREPARATION</p><h1>{title}</h1><form onSubmit={submit}>{mode === 'register' && <label>Name<input name="name" minLength={2} required /></label>}{!['verify-email'].includes(mode) && <label>Email<input name="email" type="email" required /></label>}{['login','register','reset-password'].includes(mode) && <label>Password<input name="password" type="password" minLength={12} required /></label>}{['verify-email','reset-password'].includes(mode) && <label>Token<input name="token" required /></label>}<button disabled={busy}>{busy ? 'Please wait…' : mode === 'login' ? 'Sign in' : mode === 'register' ? 'Create account' : 'Continue'}</button></form>{message && <p className="form-message">{message}</p>}{mode === 'login' && <p className="auth-links"><Link href="/forgot-password">Forgot password?</Link> · <Link href="/register">Create an account</Link></p>}{mode === 'register' && <p className="auth-links">Already registered? <Link href="/login">Sign in</Link></p>}</section></main>;
}
